### ISSUE TITLE
error on login if bibox is used with more than one school

### ISSUE THREAD

**Issue by cyborium** [LasseR15/bibox-to-pdf#11]
I have licenses from two schools, so after clicking on "Login" another window/dialog appears where I have to select which school I want to work with. After selecting a school and clicking on the okay button the page with my books appears (together with the logout button where the script is waiting for).
Because of the additional dialog the script does have a timeout and reports "Login credentials incorrect or a network error occurred."
[select_school.zip](https://github.com/user-attachments/files/17965537/select_school.zip)

**Comment by LasseR15** [comment]
Hi,
thank you for reporting the issue. 
I wanted to change the way I implemented the login in this project for quite some time now ;)

Could you please try again with the following command:
```
docker run --rm -it -p 4200:4200 -v ./books:/app/output/books ghcr.io/lasser15/bibox-to-pdf:develop {BOOK_ID}
```

**Comment by phill9494** [comment]
Thank you so much for your work.
When I use this command I get back a URL to paste in my browser, but there i get a localhost error. 
I am a complete noob, probably easy to fix, but I already tried starting Lxss Manager (Google said this would help fixing localhost error when using WSL)

**Comment by phill9494** [comment]
It worked, awesome! Thanks for your work! :-)

**Comment by LasseR15** [comment]
Perfect, thank you for your feedback!
Will merge it in release :)
