### ISSUE TITLE
Does Bibox watermark its content?

### ISSUE THREAD

**Issue by Nospce** [LasseR15/bibox-to-pdf#8]
Hey!
Do you know if the downloaded book images from Bibox are watermarked? 
Just asking for science.

**Comment by LasseR15** [comment]
Hi!
The images that you can download from Bibox with this tool are the same images (/pages) you see when regularly using the website (https://bibox.schule). I haven't noticed any watermarks yet.

**Comment by Nospce** [comment]
I was thinking more about hidden soft drm watermarks. My classmates would be pretty happy since we only got the "paper" books in our FiAe class, but since some publishers hide some information like the order number in their eBooks, I guess I'd better be careful.

**Comment by LasseR15** [comment]
I've checked and can say with a high degree of certainty that Bibox does not watermark the images.
The images downloaded between different accounts I have access to are the same. Also, the images downloaded with this script are downloaded without any user information as they are publicly available.
Authentication is only required to get the URLs to these images.

The only way to watermark these images would be per school or IP that downloads the images. But I really don't think they would do that.

**Comment by guidokl** [comment]
That sounds good. Thank you for your response and insight!
